/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Author1 } from './author1';
import { CommentReadWithChildSchema } from './comment-read-with-child-schema';


export interface ApplicationPostSchemasPostReadSchema { 
    id: number;
    title: string;
    communityId?: number | null;
    content?: string | null;
    author: Author1;
    images?: Array<string> | null;
    createdAt: string;
    updatedAt?: string | null;
    likes: number;
    comments?: Array<CommentReadWithChildSchema> | null;
}

