/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunityThemes } from './community-themes';


export interface CommunityUpdateSchema { 
    name?: string | null;
    themes?: Array<CommunityThemes> | null;
    tags?: Array<string> | null;
    description?: string | null;
}

