/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CommunityThemes = 'PROGRAMMING' | 'TECHNOLOGY' | 'EDUCATION' | 'SPORT' | 'OTHER';

export const CommunityThemes = {
    Programming: 'PROGRAMMING' as CommunityThemes,
    Technology: 'TECHNOLOGY' as CommunityThemes,
    Education: 'EDUCATION' as CommunityThemes,
    Sport: 'SPORT' as CommunityThemes,
    Other: 'OTHER' as CommunityThemes
};

