/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ImageType = 'BANNER' | 'AVATAR';

export const ImageType = {
    Banner: 'BANNER' as ImageType,
    Avatar: 'AVATAR' as ImageType
};

