/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageReadSchema { 
    id: number;
    userFromId: number;
    personalChatId: number;
    text: string;
    createdAt: string;
    isRead: boolean;
    updatedAt?: string | null;
}

