/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationCommunitySchemasPostReadSchema } from './application-community-schemas-post-read-schema';


export interface PagePostReadSchema { 
    items: Array<ApplicationCommunitySchemasPostReadSchema>;
    total: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

