/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationCommunitySchemasCommunityShortReadSchema } from './application-community-schemas-community-short-read-schema';


export interface PageCommunityShortReadSchema { 
    items: Array<ApplicationCommunitySchemasCommunityShortReadSchema>;
    total: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

