/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageReadSchema } from './message-read-schema';
import { UserReadSchemaShort } from './user-read-schema-short';


export interface PersonalChatReadSchema { 
    id: number;
    userFirst: UserReadSchemaShort;
    userSecond: UserReadSchemaShort;
    messages?: Array<MessageReadSchema> | null;
}

