/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostCreateSchema { 
    title: string;
    content?: string | null;
    authorId?: number | null;
    communityId?: number | null;
}

