/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserReadSchemaShort { 
    id: number;
    username: string;
    avatarUrl?: string | null;
    subscribersAmount?: number | null;
    firstName?: string | null;
    lastName?: string | null;
    isActive?: boolean | null;
    stack?: Array<string> | null;
    city?: string | null;
    description?: string | null;
}

