/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { RefreshToken } from '../model/models';
import { Token } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login For Access Token
     * 
     * @param username 
     * @param password 
     * @param grantType 
     * @param scope 
     * @param clientId 
     * @param clientSecret 
     */
    loginForAccessTokenAuthTokenPost(username: string, password: string, grantType?: string, scope?: string, clientId?: string, clientSecret?: string, extraHttpRequestParams?: any): Observable<Token>;

    /**
     * Logout
     * 
     */
    logoutAuthLogoutPost(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Refresh Token
     * 
     * @param refreshToken 
     */
    refreshTokenAuthRefreshPost(refreshToken: RefreshToken, extraHttpRequestParams?: any): Observable<Token>;

}
