/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { PersonalChatReadSchema } from '../model/models';
import { PersonalChatReadShortSchema } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChatServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Personal Chat
     * 
     * @param userId 
     */
    createPersonalChatChatUserIdPost(userId: number, extraHttpRequestParams?: any): Observable<PersonalChatReadSchema>;

    /**
     * Get Chats
     * 
     */
    getChatsChatGetMyChatsGet(extraHttpRequestParams?: any): Observable<Array<PersonalChatReadShortSchema>>;

    /**
     * Read Personal Chat
     * 
     * @param chatId 
     */
    readPersonalChatChatChatIdGet(chatId: number, extraHttpRequestParams?: any): Observable<PersonalChatReadSchema>;

}
