/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommentCreateSchema } from '../model/models';
import { CommentReadSchema } from '../model/models';
import { CommentReadWithChildSchema } from '../model/models';
import { CommentUpdateSchema } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CommentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Comment
     * 
     * @param commentCreateSchema 
     */
    createCommentCommentPost(commentCreateSchema: CommentCreateSchema, extraHttpRequestParams?: any): Observable<CommentReadSchema>;

    /**
     * Delete Comment
     * 
     * @param commentId 
     */
    deleteCommentCommentCommentIdDelete(commentId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get Comment
     * 
     * @param commentId 
     */
    getCommentCommentCommentIdGet(commentId: number, extraHttpRequestParams?: any): Observable<CommentReadWithChildSchema>;

    /**
     * Update Comment
     * 
     * @param commentId 
     * @param commentUpdateSchema 
     */
    updateCommentCommentCommentIdPatch(commentId: number, commentUpdateSchema: CommentUpdateSchema, extraHttpRequestParams?: any): Observable<any>;

}
