/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { MessageReadSchema } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MessageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete My Message
     * 
     * @param messageId 
     */
    deleteMyMessageMessageMessageIdDelete(messageId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get My Message
     * 
     * @param messageId 
     */
    getMyMessageMessageMessageIdGet(messageId: number, extraHttpRequestParams?: any): Observable<MessageReadSchema>;

    /**
     * Patch My Message
     * 
     * @param messageId 
     * @param text 
     */
    patchMyMessageMessageMessageIdPatch(messageId: number, text: string, extraHttpRequestParams?: any): Observable<MessageReadSchema>;

    /**
     * Send Message
     * 
     * @param chatId 
     * @param message 
     */
    sendMessageMessageSendChatIdPost(chatId: number, message: string, extraHttpRequestParams?: any): Observable<MessageReadSchema>;

}
