/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationPostSchemasPostReadSchema } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { PostCreateSchema } from '../model/models';
import { PostUpdateSchema } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PostServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Like
     * 
     * @param postId 
     */
    createLikePostLikePostIdPost(postId: number, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Create Post
     * 
     * @param postCreateSchema 
     */
    createPostPostPost(postCreateSchema: PostCreateSchema, extraHttpRequestParams?: any): Observable<ApplicationPostSchemasPostReadSchema>;

    /**
     * Delete Image
     * 
     * @param postId 
     * @param imageUrl 
     */
    deleteImagePostDeleteImagePostIdDelete(postId: number, imageUrl: string, extraHttpRequestParams?: any): Observable<ApplicationPostSchemasPostReadSchema>;

    /**
     * Delete Like
     * 
     * @param postId 
     */
    deleteLikePostLikePostIdDelete(postId: number, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Delete Post
     * 
     * @param postId 
     */
    deletePostPostPostIdDelete(postId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get My Subscriptions Post
     * 
     */
    getMySubscriptionsPostPostMySubscriptionsGet(extraHttpRequestParams?: any): Observable<Array<ApplicationPostSchemasPostReadSchema>>;

    /**
     * Get Post
     * 
     * @param postId 
     */
    getPostPostPostIdGet(postId: number, extraHttpRequestParams?: any): Observable<ApplicationPostSchemasPostReadSchema>;

    /**
     * Get Posts
     * 
     */
    getPostsPostGet(extraHttpRequestParams?: any): Observable<Array<ApplicationPostSchemasPostReadSchema>>;

    /**
     * Load Image
     * 
     * @param postId 
     * @param image 
     */
    loadImagePostUploadImagePostIdPost(postId: number, image: Blob, extraHttpRequestParams?: any): Observable<ApplicationPostSchemasPostReadSchema>;

    /**
     * Update Post
     * 
     * @param postId 
     * @param postUpdateSchema 
     */
    updatePostPostPostIdPatch(postId: number, postUpdateSchema: PostUpdateSchema, extraHttpRequestParams?: any): Observable<ApplicationPostSchemasPostReadSchema>;

}
